// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Gl_xlao_LNdNiJu6bInKRZ2vMtmPR4',
    appId: '1:377087127626:web:83ce3417fd6cbf9be0f6b3',
    messagingSenderId: '377087127626',
    projectId: 'reflection-on-faith',
    authDomain: 'reflection-on-faith.firebaseapp.com',
    storageBucket: 'reflection-on-faith.firebasestorage.app',
    measurementId: 'G-6QD4DV26F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_nTHB_CclhRjdtq2p2AZoLRSb1l4-Ds',
    appId: '1:377087127626:android:beb18cfdd222bd89e0f6b3',
    messagingSenderId: '377087127626',
    projectId: 'reflection-on-faith',
    storageBucket: 'reflection-on-faith.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XoHX5b38m9ejozpmqJ8jzFki0esU9NU',
    appId: '1:377087127626:ios:379ad1a616c4b9b2e0f6b3',
    messagingSenderId: '377087127626',
    projectId: 'reflection-on-faith',
    storageBucket: 'reflection-on-faith.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XoHX5b38m9ejozpmqJ8jzFki0esU9NU',
    appId: '1:377087127626:ios:379ad1a616c4b9b2e0f6b3',
    messagingSenderId: '377087127626',
    projectId: 'reflection-on-faith',
    storageBucket: 'reflection-on-faith.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Gl_xlao_LNdNiJu6bInKRZ2vMtmPR4',
    appId: '1:377087127626:web:68ba243e43c17109e0f6b3',
    messagingSenderId: '377087127626',
    projectId: 'reflection-on-faith',
    authDomain: 'reflection-on-faith.firebaseapp.com',
    storageBucket: 'reflection-on-faith.firebasestorage.app',
    measurementId: 'G-SNEK800DDQ',
  );
}
